name = "alliance-base-designer"
compatibility_date = "2024-11-01"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "DESIGNS"
id = "REPLACE_WITH_DESIGNS_KV_ID"

[[kv_namespaces]]
binding = "ROSTER"
id = "REPLACE_WITH_ROSTER_KV_ID"

[[kv_namespaces]]
binding = "REDEEMLOG"
id = "REPLACE_WITH_REDEEMLOG_KV_ID"

[vars]
ALLOW_WRITE = "true"
